overAll/src/test/java/mainPack/AppTest.java

test commit

---

liashenkoEProj/src/test/java/mainPack/AppTest.java

Lyashenko e 12 02

---

chepikProj/src/main/java/mainPack/App.java

Chepik 12 02

---

grebenukProj/src/test/java/mainPack/AppTest.java

Grebeniuk 12 02

---

skliarProj/src/test/java/mainPack/AppTest.java

Skliar 12 02

---

borukProj/src/test/java/mainPack/AppTest.java

First pull request
@tradulenko

Boruk 12 02

---

kuharProj/src/test/java/mainPack/AppTest.java

Kuhar 12 02

---

duhinProj/src/test/java/mainPack/AppTest.java

Dukhnin 12 02

---

gorbanProj/src/test/java/mainPack/AppTest.java

Gorban 12 02

---

bulatetskiiProj/src/test/java/mainPack/AppTest.java

Bulatetskyi 12 02

---

golubevaProj/src/test/java/mainPack/AppTest.java

Golubeva 12 02

---

skibaProj/src/test/java/mainPack/AppTest.java

Skiba 12 02

---

ianchukProj/src/test/java/mainPack/AppTest.java

Yanchuk 12 02

---

ovramenkoProj/src/test/java/mainPack/AppTest.java

Ovramenko 12 02 2019

---

erchenkoProj/src/test/java/mainPack/AppTest.java

12.02.2019 yerchenko

---

prilipkoProj/src/main/java/mainPack/App.java

Prylipko_12022019

---

liashenkoSProj/src/main/java/mainPack/App.java

Lyashenco s 12 02

---

overAll/src/test/java/mainPack/AppTest.java

Radulenko 12 02

---

skibaProj/pom.xml

first test

---

kimProj/src/main/java/pages/HomePage.java
kimProj/src/main/java/pages/LoginPage.java
kimProj/src/main/java/pages/ParentPage.java
kimProj/src/test/java/login/loginWithPageObject.java
kimProj/src/test/java/parentTest/ParentTest.java

Kim 21 02 2019

---

skibaProj/Domashka8/test_cases.txt
skibaProj/UIMapping.properties
skibaProj/src/main/java/pages/HomePage.java
skibaProj/src/main/java/pages/LoginPage.java
skibaProj/src/main/java/pages/ParentPage.java
skibaProj/src/test/java/login/Login.java
skibaProj/src/test/java/login/LoginWithPageObject.java
skibaProj/src/test/java/parentTest/ParentTest.java

first test with PageObject + test_cases translation

---

liashenkoSProj/pom.xml
liashenkoSProj/src/main/java/libs/ActionsWithOurElements.java
liashenkoSProj/src/main/java/pages/LoginPage.java
liashenkoSProj/src/main/java/pages/PerentPage.java
liashenkoSProj/src/resources/log4j.properties
liashenkoSProj/src/test/java/parentTest/ParentTest.java

First Test with PageObject and improvement

---

duhinProj/pom.xml
duhinProj/src/main/java/libs/ActionsWithOurElements.java
duhinProj/src/main/java/pages/LoginPage.java
duhinProj/src/main/java/pages/ParentPage.java
duhinProj/src/resources/log4j.properties

refractoring login page

---

grebenukProj/pom.xml
grebenukProj/src/main/java/libs/ActionsWithOurElements.java
grebenukProj/src/main/java/pages/LoginPage.java
grebenukProj/src/main/java/pages/ParentPage.java
grebenukProj/src/resources/log4j.properties

@tradulenko 
Taras y menia oshibka s vyhodom iz brayzera - crashitsia test

Hrebeniuk 26022019

---

kusnetsovProj/pom.xml
kusnetsovProj/src/main/java/libs/ActionsWithOurElements.java
kusnetsovProj/src/main/java/pages/LoginPage.java
kusnetsovProj/src/main/java/pages/ParentPage.java
kusnetsovProj/src/resourses/log4j.properties
kusnetsovProj/src/test/java/parentTest/ParentTest.java

refactoring test

---

kimProj/pom.xml
kimProj/src/main/java/libs/ActionsWithElements.java
kimProj/src/main/java/pages/HomePage.java
kimProj/src/main/java/pages/LoginPage.java
kimProj/src/main/java/pages/ParentPage.java
kimProj/src/test/java/login/loginWithPageObject.java

Kim 28 02 2019

---

liashenkoSProj/pom.xml
liashenkoSProj/src/main/java/libs/ActionsWithOurElements.java
liashenkoSProj/src/main/java/pages/HomePage.java
liashenkoSProj/src/main/java/pages/LoginPage.java
liashenkoSProj/src/test/java/login/LoginWithPageObject.java

First Test with PageObject and improvement.version1

---

duhinProj/pom.xml
duhinProj/src/main/java/libs/ActionsWithOurElements.java
duhinProj/src/main/java/pages/HomePage.java
duhinProj/src/main/java/pages/LoginPage.java
duhinProj/src/main/java/pages/ParentPage.java
duhinProj/src/test/java/login/LoginWithPageObject.java

invalid login with page object

---

grebenukProj/pom.xml
grebenukProj/src/main/java/libs/ActionsWithOurElements.java
grebenukProj/src/main/java/pages/HomePage.java
grebenukProj/src/main/java/pages/LoginPage.java
grebenukProj/src/main/java/pages/ParentPage.java
grebenukProj/src/test/java/login/LoginWithPageObject.java
grebenukProj/src/test/java/parentTest/ParentTest.java

@tradulenko 
Last day of winter
Add loggers to Parent Page, invalid login with page object

Work after 28.02.

---

liashenkoEProj/src/main/java/libs/ActionsWithOurElements.java
liashenkoEProj/src/main/java/mainPack/pages/HomePage.java
liashenkoEProj/src/main/java/mainPack/pages/LoginPages.java
liashenkoEProj/src/main/java/mainPack/pages/SettingPage.java
liashenkoEProj/src/main/java/mainPack/pages/VocabularyPage.java
liashenkoEProj/src/test/java/parentTest/ParentTest.java
liashenkoEProj/src/test/java/setting/SettingWithPageObject.java

Lyashenkoe28 02

---

liashenkoSProj/src/main/java/libs/ActionsWithOurElements.java
liashenkoSProj/src/main/java/pages/DealPage.java
liashenkoSProj/src/main/java/pages/EditSparePage.java
liashenkoSProj/src/main/java/pages/HomePage.java
liashenkoSProj/src/main/java/pages/SparPage.java
liashenkoSProj/src/main/java/pages/VocabularyPage.java
liashenkoSProj/src/test/java/login/LoginWithPageObject.java
liashenkoSProj/src/test/java/parentTest/ParentTest.java
liashenkoSProj/src/test/java/spare/AddNewSpare.java

Lyashenko s 02 03

---

skliarProj/src/main/java/libs/ActionsWithOurElements.java
skliarProj/src/main/java/pages/EditSparePage.java
skliarProj/src/main/java/pages/HomePage.java
skliarProj/src/main/java/pages/SparePage.java
skliarProj/src/test/java/parentTest/ParentTest.java
skliarProj/src/test/java/sparSpare/AddNewSpare.java

Добавлен тест "Добавление Запчасти" урок от 5.03.2019

Add Test AddSpare

---

borukProj/src/main/java/libs/ActionsWithOurElements.java
borukProj/src/main/java/pages/EditSparePage.java
borukProj/src/main/java/pages/HomePage.java
borukProj/src/main/java/pages/LoginPage.java
borukProj/src/main/java/pages/SparePage.java
borukProj/src/test/java/parentTest/ParentTest.java
borukProj/src/test/java/spareTest/AddNewSpare.java

Boruk 26 02

---

liashenkoSProj/src/main/java/libs/ActionsWithOurElements.java
liashenkoSProj/src/main/java/libs/Utils.java
liashenkoSProj/src/test/java/spare/AddNewSpare.java

Lyashenco s 12 03

---

kimProj/src/main/java/libs/ActionsWithElements.java
kimProj/src/main/java/libs/Utils.java
kimProj/src/test/java/spareTest/AddNewSpare.java

Kim lesson 12 03 2019

---

ovramenkoProj/src/main/java/libs/ActionsWithOurElements.java
ovramenkoProj/src/main/java/libs/Utils.java
ovramenkoProj/src/test/java/spareTest/AddNewSpare.java

add radio-buttons commit

---

prilipkoProj/src/main/java/libs/ActionsWithOurElements.java
prilipkoProj/src/main/java/pages/dictionary/providersPage/ProvidersEditPage.java
prilipkoProj/src/test/java/createProviders/CreateProviders.java
prilipkoProj/src/test/java/spareTest/AddNewSpare.java

Add WebDriverWait method

---

grebenukProj/src/main/java/libs/ActionsWithOurElements.java
grebenukProj/src/main/java/libs/Utils.java
grebenukProj/src/test/java/spareTest/AddNewSpare.java

Added method for checkbox state, added yavnoe ozidanie, added UTILS

Work after 12.03.

---

overAll/src/main/java/libs/ActionsWithOurElements.java
prilipkoProj/pom.xml
prilipkoProj/src/main/java/libs/ActionsWithOurElements.java
prilipkoProj/src/main/java/libs/ConfigData.java
prilipkoProj/src/main/java/libs/Database.java
prilipkoProj/src/main/java/libs/UtilsForDB.java
prilipkoProj/src/resources/config.properties
prilipkoProj/src/test/java/login/LoginWithParam.java
prilipkoProj/src/test/java/parentTest/ParentTest.java
prilipkoProj/src/test/java/suites/SmokeSuite.java
prilipkoProj/src/test/java/testDB/TestDB.java

Work with DB and test API
